### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_support#1]
This will be a static page done using NuxtJS, and will help people collect all the necessary info before they write a message.

- Home page: a list of squares representing our products, you click on one square and get to the next page
- Marketplaces: a grid of market places the product is in.
- OS: a grid of squares listing all the Linux OS, you click on one and go to the next page
- OS Version: on this page people can wrtie the version of the OS they are using, and bellow the imput page you have a linux command showing how to get the version. The command is OS specific, so we need a nice JSON file with the mapping.
- Product Version: on this page you get to write the version of the OS you are using, and similar to OS, it is product specific.

# General idea

- The idea is to make the site easily extendable, by having structured JSON files with all the data. So if something new comes a long we have to just edit the JSON file to add it to the site.
- The page needs to be rendered with all the data to make it so the Search Engines can see it.
- Each time the user makes a change on the site you save in the cookie the information entered as a JSON object, this way they don't lose their progress. 

# Sketches

![Sketches 13](https://user-images.githubusercontent.com/411114/71572867-68a6ee00-2ae1-11ea-9e05-fa455c621510.png)
![Sketches 14](https://user-images.githubusercontent.com/411114/71572868-68a6ee00-2ae1-11ea-8661-78e278e1f330.png)
![Sketches 15](https://user-images.githubusercontent.com/411114/71572869-693f8480-2ae1-11ea-9003-fc7f8a891563.png)
![Sketches 16](https://user-images.githubusercontent.com/411114/71572870-693f8480-2ae1-11ea-8630-883298fa643b.png)
![Sketches 17](https://user-images.githubusercontent.com/411114/71572871-693f8480-2ae1-11ea-8196-b5e2def28d67.png)

**Comment by davidgatti** [comment]
OK, testing it and it is working, looking promising. Lets have some improvements:

So the flow is wrong based on the description above. The page is for sure clickable, but it has the wrong things. The home page is correct, but then we marketplaces, like AWS and Azure. an then a grid o linux OS, line Amazon Linux 2, Debian, Fedora, CentOS etc. Not sure what went wrogn here, but I'd like for you to re read the original description and this time follow the description. If something is unclear let me know I can improve it. 

# What version

for the section where we ask for the version, add a list fo example commands, for example `uname -r`, but make this as a JSON file that is easy to edit for each system. 

# JSON to describe it all

For each page, make a JSON file that describes what needs to be listed on the page so it is easy to add new items. and the JSON array should have all the info, name, description, path to the image file etc. as complete as possible.

# URL path

Lets make the URL pat like this `name_name_name` and not cammelthough. 

# Refreshing the page needs to remember the stat.

When I refresh the page I go back to the home page. this should not happened until I submit the form, submission should reset all the data, but until then it should remember the page you left, and the data that was selected.

**Comment by rheckart** [comment]
> The home page is correct, but then we marketplaces, like AWS and Azure.

So the marketplaces step was unclear (didn't specify what items should be in there) _and_ it wasn't in the sketches, so that's why that was missed.

> OS: a grid of squares listing all the Linux OS, you click on one and go to the next page

I had mis-read the docs for this step to just list the Linux OSes, but all of this is in a config file named _data/operatingSystems.json_ that has the name, path to the image and version check instructions (like the `uname -r` you specified), so this is _easily_ changeable. Do you have a list of what Linux distros you want to display? And do you have a list of version check instructions for them?

URL path: I'm not sure what you mean by this. What URLs are you talking about?

> Refreshing the page needs to remember the stat.

I will try and remedy this. The data is stored in the Vuex store but if you want it to be refresh-proof, there will have to be data saved to the user's local store and then rehydrated on load to reset to the correct route.

**Comment by davidgatti** [comment]
1. By url I mean in the browser example.com/somethinbgElse, to something_else
2. About the data store yes, that ius what I want. Last year I did a page where we hade a bunch of steps like this, and I did saved a JSON object As cookie, and I was able to keep track ov everything untill the page was finally submited. I'd like the same, and you can use the browser DB, works forme if this framework has native support for it.
3. Regarding a lsit of OSes etc, no, just add fake data, and I will update this myself.

**Comment by rheckart** [comment]
I just pushed changes to the master branch to handle all three issues. The application now saves state to localStorage, specifically under the key _0x4447_webpage_support_. The state is cleared once the user clicks on the Send Report button. 

In addition, the page names are now all underscore and not camel cased.

I added a Marketplace step and put Azure and AWS in as items. To change those items, there is a file named _marketplaces.json_ in the _data_ folder that contains the name and image for each marketplace.

To change the list of OSes and Products, as well as the Version Check Instructions for them, look at the _operatingSystems.json_ and _products.json_ files, also in the _data_ folder.

**Comment by davidgatti** [comment]
OK, looking nice, and after playing with the site, here are some things to modify:

# Add bread crumbs

![Screen Shot 2020-02-02 at 5 24 55 PM](https://user-images.githubusercontent.com/411114/73611369-71f41080-45e1-11ea-8273-048c7ea7102b.png)

# remove line of text

![Screen Shot 2020-02-02 at 5 24 34 PM](https://user-images.githubusercontent.com/411114/73611377-80422c80-45e1-11ea-9472-642b37cbe7a7.png)

# Remove this line of text to

![Screen Shot 2020-02-02 at 5 25 35 PM](https://user-images.githubusercontent.com/411114/73611383-8e904880-45e1-11ea-8663-f38ea0e8c62c.png)

# Remove this two pages (bare with me)

![Screen Shot 2020-02-02 at 5 26 24 PM](https://user-images.githubusercontent.com/411114/73611385-9ea82800-45e1-11ea-863d-c8a74951efa0.png)
![Screen Shot 2020-02-02 at 5 26 57 PM](https://user-images.githubusercontent.com/411114/73611386-9ea82800-45e1-11ea-813a-52bd78b34fdc.png)

# Add this two pages now

- after the home page, when you select the product, show a list of version for the selected product, using a JOSN array
- do the same after you select the OS. This way et say you select windows, the next page shows a list of version, like Windows 10, Windows 7, Windows 95 etc. Same goes for MacOS. For linux, we need an exception, since we need an additional step, a list of distributions (from JSON), and when you select the distribution, then the next page shows a list ov version for that distribution.

PLEASE PLEAE PLEAE, read this last point about Linux carefully.

# Add a thank you page

After the form is submited, add a thank you page, that has a tile with the thank you, and bellow a short message (type whatever, I'll change it to something final later)

**Comment by rheckart** [comment]
I've almost got this working but I have a question: when they select Linux and choose their distro, how would you like the versions for the distro to show? The other pages have a selection with an image that you can click on. In this case, we probably won't have an image, so how would you like to display the distro versions?

**Comment by davidgatti** [comment]
1. Use a radial button, and then we can style it as something good looking :)
2. Hmm, right now lets do the simplest coding version, and then we can see.
3. Same thing, simpler code, and then we can decide how to go about it.

**Comment by rheckart** [comment]
I did some more work on the radio buttons but I ran into an issue that I might need another set of eyes on. If you look at the _linux-distro_ branch, in store/index.js getters section, there is a bunch of console.log statements around line 94. For some reason, when clicking on the different distros for Linux (Ubuntu or Red Hat), when clicking back and forth, sometimes the objects in `stuff` and inside the `forEach` loop end up getting the same `name` property.

I've looked at this for a good while and can't figure out why the name property is the issue (the other properties seem to be mapped correctly). I pasted an image of the dev console showing the duplication when you click the different distros in the browser:

![image](https://user-images.githubusercontent.com/942100/74398553-fdda1980-4de5-11ea-930b-a6ec59735480.png)

**Comment by davidgatti** [comment]
Sorry but I don't have the bandwidth to help you with this. And for the future, if you mention liens of code, please provide a GitHub URL to the line you are referring to to make it easier for someone else to get where they need to be.

Some tips to consider:

- If in your code you have if and elses, try to rewrite the code without the use of else. to simplify the code. Here is an explanation how to go about it and why: https://foundation.0x4447.com/departments/programers.html#else-is-not-allowed.
- Don't reuse code, copy and paste, and modify if needed, more on this here: https://foundation.0x4447.com/departments/programers.html#no-clean-code-stop-reusing
- Go over your code, and comment each line of code, this will help you organize your thoughts, and should help you figure out the problem, more on this here: https://foundation.0x4447.com/departments/programers.html#comments

**Comment by rheckart** [comment]
I figured it out. I merged the changes for everything to master.

**Comment by davidgatti** [comment]
Nice!
