### ISSUE TITLE
Invoke the lambda

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_support#4]
So it is time to use the AWS SDK in the browser to invoke the lambda function. To do so, reference this page that I did https://github.com/0x4447-office/0x4447_webpage_home/blob/development/_input/views/contact.html, to see how it should be done. 

- Right now the name of the function is irrelevant.
- We need support for a .env file.

**Comment by rheckart** [comment]
I made the changes to pages\issue.vue using your contact.html example. On failure, I have it show an alert to the user. I don't have a Lambda function or backing store setup on AWS, so I wasn't able to test the actual save success.

All changes have been pushed to the master branch.

**Comment by davidgatti** [comment]
OK, I'll check it out and then make a lambda so you can trigger it

**Comment by davidgatti** [comment]
OK, this is the name of the lambda `0x_support_submit`, and this is the Identity pool ID 
`us-east-1:ee718366-d831-42f6-9ef5-2dec0cbaddf4` that you need to use in JS.

**Comment by rheckart** [comment]
I used those settings and you _should_ see two messages posted. On the first one, I had an error that I have just pushed a small change up for.

Also, I just noticed that there isn't anywhere for the user to put their name and contact info. Where  would you like to put it?

**Comment by davidgatti** [comment]
HAHA lol :D good point :) add another step then, before the message, `personal information`, and ask only for the name and email with HTML5 validation, no code for valdiation.

**Comment by rheckart** [comment]
I changed the /nuxt.config.js and added an `env` section that has the AWS information in it for easy changing by a CI tool. I tried to post an issue up to test it and got a credentials error back (OPTIONS https://cognito-identity.us-east.amazonaws.com/ net::ERR_NAME_NOT_RESOLVED). As you can see from the screenshot, the security information appears to be correct:

![image](https://user-images.githubusercontent.com/942100/75830813-cd9bf000-5d7f-11ea-860e-8d4601b0ac7f.png)

**Comment by davidgatti** [comment]
The region is wrong, you are missing `-1` :) will fix it.
