### ISSUE TITLE
Research, how to configure S3 and CloudFront

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_support#6]
Could you spend up to 2h to find out a documentation or article where they describe how to deploy the static version on S3 with CloudFront in a way that each page gets loaded separatelly.

**Comment by rheckart** [comment]
This is actually an easy one to accomplish as they already have documentation about how to do exactly that: [https://nuxtjs.org/faq/deployment-aws-s3-cloudfront](https://nuxtjs.org/faq/deployment-aws-s3-cloudfront)

You do this after a `npm run generate`

**Comment by davidgatti** [comment]
This is what I wanted - thx, sadly it is not what I was looking for. the way they build the site dose not work as it should - I'll figure out. Right now I'm not impressed with this framework, I hope they did it right, but it seams they have have a hard time think outside the singe page idea. I hope I'm just missing something. We shall see this weekend what I can come up with :)
